Attribute VB_Name = "Module1"
'---------------------------------------------------------------------------------------
' Module    : Module1
' Author    : beededea
' Date      : 08/08/2026
' Purpose   : mainly for property handling plus a useful function or two
'---------------------------------------------------------------------------------------

Option Explicit

' using this API as it is available in Windows XP and above, suitable for ReactOS
Private Declare Function RtlGenRandom Lib "advapi32.dll" Alias "SystemFunction036" ( _
    ByRef Buffer As Any, _
    ByVal Length As Long) As Long


' General member property variables declared

Private m_sgsWindowsStartup As String
Private m_sgsAlertMsgBox As String
Private m_sgsRegularTesting As String
Private m_sgsAutomaticRemoval As String
Private m_sgsAutomaticGeneration As String
Private m_sgsGDIDInterval As String
Private m_sgsAutoGeneratedGDID As String
Private m_sgsOriginalGDID As String
Private m_sgbFirstTimeRun As Boolean


'---------------------------------------------------------------------------------------
' Procedure : gbFirstTimeRun
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gbFirstTimeRun() As Boolean

    On Error GoTo gbFirstTimeRun_Error

    gbFirstTimeRun = m_sgbFirstTimeRun

    On Error GoTo 0
    Exit Property

gbFirstTimeRun_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gbFirstTimeRun of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gbFirstTimeRun
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gbFirstTimeRun(ByVal sgbFirstTimeRun As Boolean)

    On Error GoTo gbFirstTimeRun_Error

    m_sgbFirstTimeRun = sgbFirstTimeRun

    On Error GoTo 0
    Exit Property

gbFirstTimeRun_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gbFirstTimeRun of Module Module1"

End Property


'---------------------------------------------------------------------------------------
' Procedure : gsOriginalGDID
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsOriginalGDID() As String

    On Error GoTo gsOriginalGDID_Error

    gsOriginalGDID = m_sgsOriginalGDID

    On Error GoTo 0
    Exit Property

gsOriginalGDID_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsOriginalGDID of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsOriginalGDID
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsOriginalGDID(ByVal sgsOriginalGDID As String)

    On Error GoTo gsOriginalGDID_Error

    m_sgsOriginalGDID = sgsOriginalGDID

    On Error GoTo 0
    Exit Property

gsOriginalGDID_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsOriginalGDID of Module Module1"

End Property







'---------------------------------------------------------------------------------------
' Procedure : gsGDIDInterval
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsGDIDInterval() As String

    On Error GoTo gsGDIDInterval_Error

    gsGDIDInterval = m_sgsGDIDInterval

    On Error GoTo 0
    Exit Property

gsGDIDInterval_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsGDIDInterval of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsAutoGeneratedGDID
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsGDIDInterval(ByVal sgsGDIDInterval As String)

    On Error GoTo gsGDIDInterval_Error

    m_sgsGDIDInterval = sgsGDIDInterval

    On Error GoTo 0
    Exit Property

gsGDIDInterval_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsGDIDInterval of Module Module1"

End Property


'---------------------------------------------------------------------------------------
' Procedure : gsAutoGeneratedGDID
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsAutoGeneratedGDID() As String

    On Error GoTo gsAutoGeneratedGDID_Error

    gsAutoGeneratedGDID = m_sgsAutoGeneratedGDID

    On Error GoTo 0
    Exit Property

gsAutoGeneratedGDID_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAutoGeneratedGDID of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsAutoGeneratedGDID
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsAutoGeneratedGDID(ByVal sgsAutoGeneratedGDID As String)

    On Error GoTo gsAutoGeneratedGDID_Error

    m_sgsAutoGeneratedGDID = sgsAutoGeneratedGDID

    On Error GoTo 0
    Exit Property

gsAutoGeneratedGDID_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAutoGeneratedGDID of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsWindowsStartup
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsWindowsStartup() As String

    On Error GoTo gsWindowsStartup_Error

    gsWindowsStartup = m_sgsWindowsStartup

    On Error GoTo 0
    Exit Property

gsWindowsStartup_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsWindowsStartup of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsWindowsStartup
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsWindowsStartup(ByVal sgsWindowsStartup As String)

    On Error GoTo gsWindowsStartup_Error

    m_sgsWindowsStartup = sgsWindowsStartup

    On Error GoTo 0
    Exit Property

gsWindowsStartup_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsWindowsStartup of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsAlertMsgBox
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsAlertMsgBox() As String

    On Error GoTo gsAlertMsgBox_Error

    gsAlertMsgBox = m_sgsAlertMsgBox

    On Error GoTo 0
    Exit Property

gsAlertMsgBox_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAlertMsgBox of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsAlertMsgBox
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsAlertMsgBox(ByVal sgsAlertMsgBox As String)

    On Error GoTo gsAlertMsgBox_Error

    m_sgsAlertMsgBox = sgsAlertMsgBox

    On Error GoTo 0
    Exit Property

gsAlertMsgBox_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAlertMsgBox of Module Module1"

End Property



'---------------------------------------------------------------------------------------
' Procedure : gsAutomaticGeneration
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsAutomaticGeneration() As String

    On Error GoTo gsAutomaticGeneration_Error

    gsAutomaticGeneration = m_sgsAutomaticGeneration

    On Error GoTo 0
    Exit Property

gsAutomaticGeneration_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAutomaticGeneration of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsAutomaticGeneration
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsAutomaticGeneration(ByVal sgsAutomaticGeneration As String)

    On Error GoTo gsAutomaticGeneration_Error

    m_sgsAutomaticGeneration = sgsAutomaticGeneration

    On Error GoTo 0
    Exit Property

gsAutomaticGeneration_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAutomaticGeneration of Module Module1"

End Property



'---------------------------------------------------------------------------------------
' Procedure : gsAutomaticRemoval
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsAutomaticRemoval() As String

    On Error GoTo gsAutomaticRemoval_Error

    gsAutomaticRemoval = m_sgsAutomaticRemoval

    On Error GoTo 0
    Exit Property

gsAutomaticRemoval_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAutomaticRemoval of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsAutomaticRemoval
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsAutomaticRemoval(ByVal sgsAutomaticRemoval As String)

    On Error GoTo gsAutomaticRemoval_Error

    m_sgsAutomaticRemoval = sgsAutomaticRemoval

    On Error GoTo 0
    Exit Property

gsAutomaticRemoval_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsAutomaticRemoval of Module Module1"

End Property





'---------------------------------------------------------------------------------------
' Procedure : gsRegularTesting
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Get gsRegularTesting() As String

    On Error GoTo gsRegularTesting_Error

    gsRegularTesting = m_sgsRegularTesting

    On Error GoTo 0
    Exit Property

gsRegularTesting_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsRegularTesting of Module Module1"

End Property

'---------------------------------------------------------------------------------------
' Procedure : gsRegularTesting
' Author    : beededea
' Date      : 08/10/2025
' Purpose   :
'---------------------------------------------------------------------------------------
'
Public Property Let gsRegularTesting(ByVal sgsRegularTesting As String)

    On Error GoTo gsRegularTesting_Error

    m_sgsRegularTesting = sgsRegularTesting

    On Error GoTo 0
    Exit Property

gsRegularTesting_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure gsRegularTesting of Module Module1"

End Property



'---------------------------------------------------------------------------------------
' Procedure : SecureRandomHex64
' Author    : chatGPT
' Date      : 09/08/2026
' Purpose   : builds a 64bit 16 character ID string
'---------------------------------------------------------------------------------------
'
Public Function SecureRandomHex64() As String

    Dim b(7) As Byte
    Dim i As Long

    On Error GoTo SecureRandomHex64_Error

    ' returns a random number and populates an array of 8 byte buffers
    If RtlGenRandom(b(0), 8) <> 0 Then 'success
        For i = 0 To 7
            ' builds a string of hex pairs, padding with zero if required.
            SecureRandomHex64 = SecureRandomHex64 & Right$("0" & Hex$(b(i)), 2)
        Next
    End If

    On Error GoTo 0
    Exit Function

SecureRandomHex64_Error:

     MsgBox "Error " & Err.Number & " (" & Err.Description & ") in procedure SecureRandomHex64 of Module Module1"

End Function
